# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'PolyvCloudClassDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  pod 'MBProgressHUD', '~> 1.1.0'
  
  # Pods for PolyvCloudClassDemo
  pod 'PolyvCloudClassSDK', '~> 0.5.0' # polyv 云课堂 SDK
end
