# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'PolyvCloudClassDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  pod 'Masonry', '~> 1.1.0'
  pod 'SDWebImage', '4.4.0'
  
  # Pods for PolyvCloudClassDemo
  pod 'PolyvCloudClassSDK', '~> 0.16.0' # polyv 云课堂 SDK

end
